### ISSUE TITLE
Some problems with running this code

### ISSUE THREAD

**Issue by Alan-JW** [JedMills/MTFL-For-Personalised-DNNs#1]
Hello @JedMills,
 thank you so much for your contribution to the Multi-tasking Federal Learning Community.I encountered the following problems while running your code in CIFAR-10,

The command line is as follows,   'python main.py -dset cifar10 -alg fedavg -C 1.0 -B 150 -T 600 -E 2 -device cpu -W 200 -seed 2 -lr 0.1 -noisy_frac 0.1 -bn_private usyb'

1. The first problem I encountered is as follows,
'FileNotFoundError: [Errno 2] No such file or directory: '../CIFAR10_data/data_batch_1.pkl''
![q1](https://user-images.githubusercontent.com/74579183/133605717-cf5bcb23-861d-4b88-949e-d7ff0e3de913.png)

However, I have downloaded the correct data package from the official website of A data, decompressed it and placed it in the correct folder, as shown in the picture below,
![q1-1](https://user-images.githubusercontent.com/74579183/133606333-678fc6fd-abe3-469c-853b-f86909b64c7a.png)

2. In view of the above problems, I made modifications as shown in the picture below,
    "fnames = ['/data_batch_1.pkl', '/data_batch_2.pkl', '/data_batch_3.pkl',
          '/data_batch_4.pkl', '/data_batch_5.pkl']"   ---->     "fnames = ['/data_batch_1', '/data_batch_2', '/data_batch_3',
          '/data_batch_4', '/data_batch_5']"
![q2](https://user-images.githubusercontent.com/74579183/133607299-5b4d9d8f-8888-4949-a040-68239280ddd9.png)

However, I ran into a new problem,('UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 6: ordinal not in range(128)'), as shown in the picture below,
![q2-1](https://user-images.githubusercontent.com/74579183/133607200-d009954c-4c70-43c8-8ab5-fe474bd54f2a.png)

Finally, I would like to ask you how to solve this problem.

Thank you very much for your answer.

**Comment by JedMills** [comment]
Hi Alan,

thanks for your email. Did you download the data from the official CIFAr10
website (https://www.cs.toronto.edu/~kriz/cifar.html)? Namely the files at:
https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz

If yes, what is your python version? It looks like a problem with pickle
being unable to read the file. The version I have been using is 3.7.5.

Did you have any trouble with MNIST?

Warm regards,
Jed

**Comment by Alan-JW** [comment]
Hi @JedMills ，
Yes, my data is downloaded from the official website of CIFAr10, and the download link is “https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz”.
My Python version is 3.7.1
![q3](https://user-images.githubusercontent.com/74579183/133747266-02473e49-dec2-4933-99ed-2639a8e12ab9.png)

I was able to run successfully in MNIST and successfully generate PKL files as shown below,
![image](https://user-images.githubusercontent.com/74579183/133747711-f36a058f-e0d4-47a1-93ce-cbc9ff54b304.png)

Thank you very much for your answer.

**Comment by JedMills** [comment]
Hi Alan,

Sorry, this was my mistake. I was loading some pre-processed CIFAR10 files,
not the raw files from the website. I've edited the code and just ran an
experiment with no problems, using the original files.

Please could you let me know if you can successfully run a CIFAR10
experiment with the updated code?

Warm regards,
Jed

**Comment by Alan-JW** [comment]
Hi, @JedMills,
Thank you for updating the code. I can successfully run a CIFAR10 experiment with the updated code.
![8af37b97070e837bb6194f491d8df7f](https://user-images.githubusercontent.com/74579183/133893205-c254b2cf-5eb2-4c0c-9693-b55bc6e3d68a.png)

By the way, I would like to ask whether the design of these parameters such as, -C,-B,-T,-E,-seed,-lr and so on, in the commands,
'python main.py -dset  mnist -alg fedavg -C 1.0 -B 150 -T 600 -E 2 -device cpu -W 200 -seed 2 -lr 0.1 -noisy_frac 0.1 -bn_private usyb'
and python main.py -dset cifar10 -alg fedavg -C 1.0 -B 150 -T 600 -E 2 -device cpu -W 200 -seed 2 -lr 0.1 -noisy_frac 0.1 -bn_private usyb''  I used in these two tests is correct to reproduce the results of your paper successfully .

Thank you very much for your answer.

**Comment by JedMills** [comment]
Hi Alan,

Are these the parameters for reproducing the results in Tables 2 and 3? If
so, we use a batch size of 20 and 1 epoch, so try:

python main.py -dset mnist -alg fedavg -C 1.0 -B 20 -T 500 -E 1 -device cpu
-W 200 -seed 2 -lr 0.1 -noisy_frac 0.1 -bn_private usyb

Warm regards,
Jed

**Comment by Alan-JW** [comment]
Hi @JedMills ,
Thank you for your reply! What are the parameters for reproducing the results in Table 4, Figure 4 and Figure 5?

Thank you very much for your answer.

**Comment by JedMills** [comment]
Hi Alan,

for Table 4, the parameters are the same, but we ran those results on a
Raspberry-Pi testbed to get the times. For Fig. 5, the parameters for
FL(FedAvg) and MTFL(FedAvg) are the same, the PerFedAvg and pFedMe
parameters tuned are given in Section 4.4. Bear in mind, we tuned the
hyperparameters for every scenario in a grid of [1.0, 0.3, 0.1, 0.03, ...]
(learning-rate for FedAvg, plus an additional hyperparameter each for
PerFedAvg and pFedMe).

Warm regards,
Jed

**Comment by Alan-JW** [comment]
Hi， @JedMills 
Ok, thank you for your reply！

**Comment by Alan-JW** [comment]
Hi @JedMills ,
I encountered a new problem running your code, as shown in the figure below，
![image](https://user-images.githubusercontent.com/74579183/134690578-4503cc9c-c293-4005-b04a-569fcca313fb.png)
![image](https://user-images.githubusercontent.com/74579183/134690606-0f0f5fd8-f5f7-4e64-8f84-7fd2c7da1b58.png)

Thank you very much for your answer.

**Comment by Alan-JW** [comment]
Hi @JedMills , solved that problem by adding this sentence 'from models import *' to file 'fl_algs.py' .

**Comment by JedMills** [comment]
Hi Alan,

thanks for letting me know - I've added the import to the main brain.

Warm regards,
Jed

**Comment by Alan-JW** [comment]
Hi @JedMills ,
Does your current open source code not include a version that runs on raspberry PI?
Could you please upload the code running on raspberry PI as a reference for our reproduction paper?

Thank you very much for your answer.

**Comment by JedMills** [comment]
Hi Alan,

unfortunately there is no open source version of the RPi code. I'm
currently working on other projects and don't have the time to tidy up and
publish the extra code. However, the current github repo should be fairly
easy to extend, running the client loop on a separate device and
communicating the global/client models using python sockets.

For further queries, please email me directly at ***@***.***

Warm regards,
Jed

**Comment by Alan-JW** [comment]
Hi Jed，
Thank you for your reply！

Yours sincerely,
Alan
