### ISSUE TITLE
Maybe fedavg has a problem

### ISSUE THREAD

**Issue by MiaJ321** [JedMills/MTFL-For-Personalised-DNNs#10]
Hello  Jed,
      I'm sorry to bother you.
      Recently we did an experiment.And I found the test ccuracy of fedavg a little strange.I don't know if there are any problems with fedavg.
      Here is the test accuracy of some algorithms.All algorithm parameters are set in the case of control variables.    
![屏幕截图 2022-10-18 173718](https://user-images.githubusercontent.com/109147675/196394756-9f149760-4017-47dd-887d-df1ec94e24d4.jpg)
      It is obvious that in Mnist database,the test accurary of fedavg is better than the other two.However,in general, in the case of non-iid, the effect of fedavg should be lower than that of other algorithms. So we think these data are a little strange. But we are not sure where the problem occurred.So we would like to ask your opinion. 
    Looking forward to your early reply. @JedMills 

Warm regards,
Mia

**Comment by JedMills** [comment]
Hi Mia,

Thanks for your question. I just answered a [similar one](https://github.com/JedMills/MTFL-For-Personalised-DNNs/issues/9) from another user. Could you read that and see if it addresses your problem?

Warm regards,
Jed

**Comment by MiaJ321** [comment]
Hi Jed,

Thank you very much for your reply. After reading your answer, my doubts have been solved.
Thanks again for your help.

Warm regards,
Mia
