### ISSUE TITLE
Some problems about the design of parameters

### ISSUE THREAD

**Issue by Yeahcy1208** [JedMills/MTFL-For-Personalised-DNNs#2]
Hello @JedMills ，
I would like to ask whether the design of these parameters such as -lr in the CIFAR10 dataset in fig.5.
like this 'python main.py -dset mnist -alg fedavg -C 1.0 -B 20 -T 500 -E 1 -device cpu -W 200 -seed 2 -lr 0.1 -noisy_frac 0.1 -bn_private usyb'.

Yours sincerely,
YeahCY

**Comment by JedMills** [comment]
Hi YeahCY,

Thanks for your query. If you go to the IEEE Xplore page for the paper (https://ieeexplore.ieee.org/abstract/document/9492755) and click on the CodeAvailable button, there is a bash script for exactly running and plotting the results from Fig. 5 a), including the correct hyperparameters. The script can be easily extended to reproduce the rest of the results from Fig. 5. 

Warm regards,
Jed

**Comment by Yeahcy1208** [comment]
Hi Jed,
Thank you very much for your answer!

**Comment by realcly** [comment]
> Hi Jed, Thank you very much for your answer!

![image](https://user-images.githubusercontent.com/59962243/176810672-415cffc6-ec1b-4769-be9b-183513b0e171.png)

Have you found the relevant operating parameters of CIFAR-10 on the paper page?  I only saw the parameters about mnist, and I ask you humbly!

Yours sincerely

**Comment by realcly** [comment]
> Hi YeahCY,
> 
> Thanks for your query. If you go to the IEEE Xplore page for the paper (https://ieeexplore.ieee.org/abstract/document/9492755) and click on the CodeAvailable button, there is a bash script for exactly running and plotting the results from Fig. 5 a), including the correct hyperparameters. The script can be easily extended to reproduce the rest of the results from Fig. 5.
> 
> Warm regards, Jed

Hi Jed,
thank you for your sharing!  You have helped me a lot!  I only found the parameters about mnist on the IEEE paper page. Where are the relevant operating parameters of CIFAR-10?  As shown in the picture above, I ask you humbly!

**Comment by JedMills** [comment]
Hi Realcly,

Apologies for the delayed reply. 

I've added the file "Fig-5-settings.md" containing all the hyperparameters used for the experiments in Fig 5. 

Warm regards,
Jed

**Comment by realcly** [comment]
Hi Jed,


Thank you so much for your reply and help!


I will continue to study your related work and research.&nbsp;


If you have any questions in the future, I hope to have the opportunity to consult and communicate with you!


Thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JedMills/MTFL-For-Personalised-DNNs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JedMills/MTFL-For-Personalised-DNNs] Some problems about the design of parameters (Issue #2)





 
Hi Realcly,
 
Apologies for the delayed reply.
 
I've added the file "Fig-5-settings.md" containing all the hyperparameters used for the experiments in Fig 5.
 
Warm regards,
 Jed

**Comment by JedMills** [comment]
Hi Realcy,

That's no problem - good luck with your work. I'll be happy to answer any future questions.

Warm regards,
Jed
