### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'set_deterministic'

### ISSUE THREAD

**Issue by realcly** [JedMills/MTFL-For-Personalised-DNNs#4]
![image](https://user-images.githubusercontent.com/59962243/176820943-881f3643-96cc-4716-9388-63713b617763.png)

Hello, I have this problem when I run the code, how can I solve it?  Thanks!  Also ask the teachers who see this question!

**Comment by JedMills** [comment]
Hi Cai,

The problem may be due to the version of pytorch used. I believe
torch.set_deterministic() has been removed in newer versions. The repo uses
pytorch 1.7.0 - which version are you using?

Warm regards,
Jed
