### ISSUE TITLE
Cifar10 reproduced with your code cannot achieve the effect in your paper

### ISSUE THREAD

**Issue by MiaJ321** [JedMills/MTFL-For-Personalised-DNNs#6]
Hello, I'm sorry to bother you. Recently we tried to reproduce cifar10 with your code. However, it is regrettable that the data we obtained cannot meet the results in your paper. The accuracy of our test data has been between 0.4 and 0.6. We don't know where the problem is. We hope you can give us an answer. Thank you very much!

The accuracy of our test data is below: 
![1](https://user-images.githubusercontent.com/109147675/185778837-ac56c7fa-0964-4077-b4a6-f97f105f47f2.jpg)

**Comment by JedMills** [comment]
Hi Mia,

Thanks for your message. What settings were you using for the simulations?
The file fig-5-settings.md contains all the hyperparameters to reproduce
the experiments shown in Fig. 5 of the paper.

Warm regards,
Jed

**Comment by MiaJ321** [comment]
Hi Jed,

Thanks for your reply.The settings we used are as follows:
The first one is -dset cifar10 -alg fedavg-adam -C 0.5 -B 20 -T 500 -E 1 -device gpu -W 400 -seed 0 -lr 0.003 -noisy_frac 0.0 -bn_private usyb -beta1 0.9 -beta2 0.999 -epsilon 1e-7.
The second one is -dset cifar10 -alg perfedavg -C 1.0 -B 20 -T 200 -E 1 -device gpu -W 200 -seed 0 -lr 0.1 -noisy_frac 0.0 -beta 0.1.
And it is a pity that the test accuracy of the two data about the setting of cifar10 is between 0.4 and 0.6, just like the photos I sent you before.
Looking forward to your early reply.

Warm regrads,
Mia

**Comment by JedMills** [comment]
Hi Mia,

As part of another issue with the code (raised by user Bhongcheng), I fixed a bug in  `data_utils.py` when loading the CIFAR10 test set. I ran the first set of settings that you quoted: 

`-dset cifar10 -alg fedavg-adam -C 0.5 -B 20 -T 500 -E 1 -device gpu -W 400 -seed 0 -lr 0.003 -noisy_frac 0.0 -bn_private usyb -beta1 0.9 -beta2 0.999 -epsilon 1e-7`,

and the accuracy reached >65% after 16 rounds, which corroborates with the relevant value in Table 2. Please could you try running again with the test-set fix and see if it's working ok?

Warm regards,
Jed

**Comment by MiaJ321** [comment]
Hi Jed,

Thanks for your reply.We ran the program again yesterday. The test accuracy was the same as that in your paper. Thank you for your patience.

Warm regrads,
Mia

**Comment by MiaJ321** [comment]
Hi Jed,

Thanks for your reply.We ran the program again yesterday. The test accuracy was the same as that in your paper. Thank you for your patience.

Warm regrads,
Mia

**Comment by JedMills** [comment]
Hi Mia,

I'm glad the programs are now working as expected. Thanks for highlighting the bug!

Warm regards,
Jed
